### ISSUE TITLE
DNS between k8's and mesos.

### ISSUE THREAD

**Issue by timothysc** [mesosphere/kubernetes-mesos#125]
The gulf between name resolution of services which may inter-operate needs to be bridged.

http://mesosphere.com/2015/01/21/mesos-dns-service-discovery/
vs. 
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns

**Comment by jdef** [comment]
xref https://github.com/mesosphere/mesos-dns/issues/62

**Comment by jdef** [comment]
#256 added discovery-info generation for tasks: experimental support discovery of pods (nothing yet for services)

**Comment by akamalov** [comment]
@jdef  is pod lookup supported using Mesos-DNS ? I can for sure ping kubernetes.mesos, but can't seem to discover any pods (sample nginx running, can't discover).

**Comment by jdef** [comment]
experimental support was added via the scheduler
flag: mesos-generate-task-discovery. it defaults to false. once enabled you
can fine-tune its behavior by setting labels and/or attributes.

https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/podtask/pod_task.go#L138

We haven't received much feedback on this feature yet, so if it's something
you find useful please post a follow-up.

**Comment by jdef** [comment]
probably an easier read:
https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/docs/discovery.md

**Comment by akamalov** [comment]
@jdef, thanks so much!

**Comment by akamalov** [comment]
@jdef  - Hey James. Modified and re-launched **km-scheduler** with ```--mesos-generate-task-discovery=true```.  

Deployed a sample application:

```
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx-http
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        k8s.mesosphere.io/discovery-name: nginx-rc
    spec:
      containers:
      - name: nginx-http
        image: nginx
        ports:
        - containerPort: 80
```

Launched application:

```
[root@node236 k8s]# kubectl create -f nginx-https2.yaml 
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30005) to serve traffic.

See http://releases.k8s.io/HEAD/docs/user-guide/services-firewalls.md for more details.
service "nginxsvc" created
replicationcontroller "nginx-rc" created
```

Check the status of pods:

```
[root@node236 k8s]# kubectl get pods -o wide
NAME             READY     STATUS    RESTARTS   AGE       NODE
nginx-rc-5uqd3   1/1       Running   0          8s        node261.local.net
[root@node236 k8s]# 
```

Display services:

```
[root@node236 k8s]# kubectl get services -o wide
NAME             CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE       SELECTOR
k8sm-scheduler   172.16.10.161   <none>        10251/TCP   1d        <none>
kubernetes       172.16.10.1     <none>        443/TCP     1d        <none>
nginxsvc         172.16.10.80    nodes         80/TCP      33s       app=nginx
[root@node236 k8s]# 
```

Try to ```nslookup``` the pod - format: ```${name}.${pod-namespace}.pod```:

```
[root@node236 k8s]# nslookup nginx-rc-5uqd3.default.pod
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find nginx-rc-5uqd3.default.pod: NXDOMAIN

[root@node236 k8s]# 

```

No dice :(
