### ISSUE TITLE
CPU, Mem resouce limit in Pod definition is not used in Scheduler.

### ISSUE THREAD

**Issue by wangqiang8511** [mesosphere/kubernetes-mesos#304]
## Problems.

Env: I have three small mesos-slaves registered with kubernetes-mesos in my test env.
I tried kubernetes cassandra examples with replicas=2.

All the two containers are scheduled to the same host. The first one can start. Second one always stucked.
The log in executor shows:

```bash
event.go:138] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"cassandra-c3r8t", UID:"8b2176ba-04e7-11e5-9403-1278f7e395e9", APIVersion:"v1beta1", ResourceVersion:"202819", FieldPath:""}): reason: 'capacityExceeded' Cannot start the pod due to exceeded capacity.
W0528 03:14:32.859860    5792 status_manager.go:59] Failed to updated pod status: error updating status for pod "cassandra-c3r8t": Pod "cassandra-c3r8t" is invalid: status.host: invalid value '': pod host cannot be changed directly
...
I0528 03:18:42.365332    5792 kubelet.go:1920] Query docker container info for pod "cassandra-c3r8t_default" failed with error (no containers exist for this pod)
I0528 03:18:42.666615    5792 kubelet.go:1920] Query docker container info for pod "cassandra-c3r8t_default" failed with error (no containers exist for this pod)
W0528 03:18:42.835143    5792 executor.go:513] Launch expired grace period of '5m0s'
```

The executor keep checking the container status, (This wont be successful since kubelet already filtered out this request according to the event in the first line of log.), util grace period timeout. the task become lost. 

In kubernetes, the pod status always pending. In apiserver, the pod status is always waiting.

## There are two issues here.

* Why capacityExceeded? 
In the definition of cassandra pods, container request cpu resources 1000, the second one request the same, I only have one cpu, so capacityExceeded.

In this case, I hope the scheduler should schedule the tasks to different host. But seems in the scheduler, the cpu, memory resource of container is hardcode to 0.25, 64M. I hope the cpu resource in pod can be used here instead of hardcode.
Currently I can only drop the cpu resource limit in pod definition.

* I hope the scheduler can do something when the task appear to be lost.

**Comment by jdef** [comment]
Can you share your pod and slave specifications?

we're poised to begin resolving this, which appears closely related:
* https://github.com/mesosphere/kubernetes-mesos/issues/68

**Comment by wangqiang8511** [comment]
Here is the rc I used.

```yaml
id: cassandra
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 4
  replicaSelector:
    name: cassandra
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: cassandra
        containers:
          - name: cassandra
            image: kubernetes/cassandra:v2
            command:
              - /run.sh
            cpu: 1000
            ports:
              - name: cql 
                containerPort: 9042
              - name: thrift
                containerPort: 9160
            volumeMounts:
              - name: data
                mountPath: /cassandra_data
            env:
              - key: MAX_HEAP_SIZE
                value: 512M
              - key: HEAP_NEWSIZE
                value: 100M
        volumes:
          - name: data
            source:
              emptyDir: {}
    labels:
      name: cassandra
```

I am using very small instance to do the test.

```bash
…5050-11092-S2 master2.mesostest         1       1002 MB         2.4 GB  a week ago           
…5050-11092-S1 master1.mesostest         1       1002 MB         2.4 GB  a week ago           
…5050-11092-S0 master0.mesostest         1       1002 MB         2.4 GB  a week ago 
```

Here is the way how kubernetes check the capacity. 

https://github.com/GoogleCloudPlatform/kubernetes/blob/v0.14.2/pkg/scheduler/predicates.go#L104-124

Here is how k8sm scheduler accept Offer
https://github.com/mesosphere/kubernetes-mesos/blob/v0.4.2/pkg/scheduler/podtask/pod_task.go#L111-137

In my thoughts, any pods with cpu limit meta more than 0.25 (250) can potentially cause problems.
The pod task may need to carry on the pod meta info to coordinate with k8s capacity check.

I am new to this, correct me if I am wrong.
