### ISSUE TITLE
port-mapping metadata is not exposed to underlying pod

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#323]
see https://github.com/GoogleCloudPlatform/kubernetes/issues/8988

A pod container has no way to discover which host ports are mapped to its container ports (it does not know what to advertise to external clients). If external clients connect via a service, this is not a problem since endpoints are terminated at HostIP:HostPort by default. However, in the case that a pod registers it's containerIP:containerPort with an external registry the model breaks: the containerIP is a host-private IP that is inaccessible outside of the host which runs the pod.

Marathon solves this by injecting environment variables into a container at run time:
* `PORT_{port-num}`
* `PORT{port-index}`
* `HOST`

There's a docker PR open to address this (except for `$HOST` information):
https://github.com/docker/docker/pull/13363

**Comment by jdef** [comment]
Marathon also has special handling for containerPort = hostPort = 0: 
* https://github.com/mesosphere/marathon/pull/1548
* https://github.com/mesosphere/marathon/pull/1468

**Comment by sushantk** [comment]
@jdef thanks for filing this ticket.

Exposing host's dynamic port into container and allowing containers to dynamically bind to a port (containerPort = hostPort = 0) is quite handy w/ some of the peer to peer applications such as multi worker storm, which uses an external service discovery software to discover and communicate with each other. This has worked beautifully in marathon, but we are working towards porting our applications to k8s because of richer constructs.

I agree that IP per pod is an ideal construct, but it is not yet proven enough to be used in big data center environments w/ many subnets and constrains on number of IP sessions at the fabric switch layer. It appears that providing an escape hatch to use something as basic as port forwarding with the above capabilities may be a good option while we experiment with overlay network (flannel, vxlan etc).

Do you think we can attempt a patch? Will this be in k8s or k8s-mesos?

**Comment by jdef** [comment]
containerPort = hostPort = 0 would violate k8s container port validation
rules:
https://github.com/GoogleCloudPlatform/kubernetes/blob/release-0.18/pkg/api/validation/validation.go#L588

for kubernetes pods, since each pod gets it's own networking stack there's
no need to randomize the containerPort. all of your pods could pick the
same containerPort w/ hostPort = 0, and k8s-mesos host-port mapping will
allocate a random port from the resource offer. what we need to be careful
of is how to expose this information to containers in the pod.

I think that at this time, the least invasive way would be for k8s to
provide additional environment variables, in the spirit of Marathon, so
that pod containers can determine the host-container port mappings. If
these environment variables are not present, then apps could fall back to
some other type of introspection (e.g. what Docker is proposing, or
something else).

The tricky bit is how to expose $HOST to the pod. If an app wants to
announce itself via an external registry, and the host has multiple IP
addresses, which IP address do we assign to $HOST in the CT environment?
Depending on where the external registry lives in the network, choosing
slave-ip-address may not be the best option. k8s-mesos could leave this up
to apps to solve for themselves. For example, an app could query a
"what-is-my-ip-address" type service to determine the ip-address that it
should use w/ an external registry. but that's annoying, who wants to run
another app? so k8s-mesos could also just pass along slave-hostname in
$HOST and if an app wants something else (because slave-hostname isn't
relevant for consumers of the external registry) then it has to do the
additional legwork.

also, what are the security implications (if any) of exposing the
slave-hostname to a user-pod?

**Comment by jdef** [comment]
another thought: downward api volume plugins (https://github.com/GoogleCloudPlatform/kubernetes/pull/5093) will land at some point, and would allow k8s-mesos to expose additional metadata via annotations. k8s-mesos could expose $HOST (I think it already does) as an annotations variable. I believe that the port mapping metadata is also already exposed via annotations.

The downside to this approach is that it creates a dependency between user pods and specific implementation of k8s.

**Comment by jdef** [comment]
pretty sure the mapping is exposed through annotations at this point (undocumented and subject to change). closing this out. please re-open if neededn

**Comment by karlkfi** [comment]
Example Annotations from a DCOS k8s pod:

```
metadata:
  annotations:
    k8s.mesosphere.io/bindingHost: 10.0.1.187
    k8s.mesosphere.io/executorId: e09b9533a059d258_k8sm-executor
    k8s.mesosphere.io/offerId: 20151005-174857-3255042058-5050-1396-O24930
    k8s.mesosphere.io/port_TCP_3000: "1025"
    k8s.mesosphere.io/portName_TCP_http: "1025"
    k8s.mesosphere.io/slaveId: 20151005-174857-3255042058-5050-1396-S0
    k8s.mesosphere.io/taskId: pod.47d717fe-6bbd-11e5-a8ce-06a96b74993f
    kubernetes.io/created-by: '{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"oinker-rc","uid":"47b6db75-6bbd-11e5-8d3b-06a96b74993f","apiVersion":"v1","resourceVersion":"1535"}}'
```
