### ISSUE TITLE
"No such image:" error when starting pods

### ISSUE THREAD

**Issue by eirslett** [mesosphere/kubernetes-mesos#558]
I've tested the manifest from [this blog post](http://kamalmarhubi.com/blog/2015/08/27/what-even-is-a-kubelet/):

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - name: log-truncator
    image: busybox
    command:
    - /bin/sh
    args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
    volumeMounts:
    - mountPath: /logdir
      name: nginx-logs
  volumes:
  - name: nginx-logs
    emptyDir: {}
```

When putting this in `manifests/nginx.yml` and then running `kubelet --config=$PWD/manifests`, it will start the pod on the node the `kubelet` command is run. (In other words, pure kubelet, not using kubernetes or mesos) So that works.

When I try running `kubectl create -f manifests/nginx.yml` (trying to start the pod in kubernetes on mesos) I get this error in the docker logs on the mesos agent:

```
docker[14739]: time="2015-10-14T11:40:26.942179078Z" level=error msg="HTTP Error" err="No such image: busybox" statusCode=404"
```
