### ISSUE TITLE
testing for v0.7.2-v1.1.5 release

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#752]
- [x] test ubercontainer failover onto another host when the original host fails (see below)
  - [x] pods should keep running on other hosts
  - [x] pods on killed host should be restarted (if backed by rc)
  - [x] dns resolution should keep working: in busybox container `nslookup kube-ui.kube-system.svc.cluster.local`
  - [x] dns resolution should work for new services: launch nginx pod and service. Test in busybox container  `nslookup nginx.default.svc.cluster.local`.
- [x] deploy `examples/guestbook`. Try posting something in the web UI.
- [x] execute `dcos kubectl version`
- [x] do 2h+ soak testing w/ [hack/resizeFrontend.sh](https://github.com/mesosphere/kubernetes-mesos/blob/master/hack/resizingFrontend.sh)
- [x] smoke test Mesos-DNS via a busybox test container executing `nslookup kubernetes.mesos`.
- [x] smoke test roles support using a simple nginx pod (see **[1]**).  Install with `dcos kubectl create -f nginxpub.yaml`, wait ~1min. and open the link "Master IP addresses:" available in CCM. One should see the nginx landing page.

**ubercontainer failover**

Find out which slave ID runs the kubernetes ubercontainer in the DCOS UI, then ssh into the node:

```
$ dcos node ssh --master-proxy --slave=xxxxxx-yyyy-4cab-b1fb-3c92a11cdd2d-S1
$ sudo systemctl stop dcos-mesos-slave.service
```

**[1]** Sample roles enabled public nginx pod `nginxpub.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginxpub
  annotations:
    k8s.mesosphere.io/roles: "slave_public"
  labels:
    app: nginxpub
spec:
  containers:
  - name: nginxpub
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
```
